[theme]
base = "light"
primaryColor = "#b25e5e"
backgroundColor = "#f6f2ea"
secondaryBackgroundColor = "#fdfbf7"
textColor = "#14110c"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
