[theme]
base = "light"
primaryColor = "#045b98"
backgroundColor = "#f9fafe"
secondaryBackgroundColor = "#ffffff"
textColor = "#12203a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
